options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _REGION: "europe-west6"
  _SERVICE: "chattender-fahrplan-mcp"
  _REPO: "apps"
  _IMAGE_NAME: "chattender-fahrplan-mcp"
  # Removed _IMAGE_TAG from here, as it contains a dynamic variable
  _JOURNEY_SERVICE_BASE: "https://journey-service-int.api.sbb.ch"

steps:
  # Build Image mit Paketo Buildpacks (kein Dockerfile nötig)
  - name: gcr.io/k8s-skaffold/pack
    args:
      - build
      # The pack build command will correctly resolve these variables at runtime
      - "europe-west6-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE_NAME}:commit-$SHORT_SHA"
      - "--path=."
      - "--builder=gcr.io/buildpacks/builder:v1"
    env:
      - GOOGLE_RUNTIME_VERSION=java21

  # This step is actually redundant if the pack build step successfully pushes the image.
  # Buildpacks usually push directly to the specified registry.
  # However, if you want to explicitly push, ensure the tag is correct.
  # For most buildpack workflows, you can remove this step.
  # If you keep it, ensure the image name matches what pack build produced.
  # - name: gcr.io/cloud-builders/docker
  #   args:
  #     - push
  #     - "europe-west6-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE_NAME}:commit-$SHORT_SHA"

  # Deploy auf Cloud Run
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: bash
    args:
      - -c
      - |
        gcloud run deploy ${_SERVICE} \
          --image europe-west6-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE_NAME}:commit-$SHORT_SHA \
          --region ${_REGION} \
          --allow-unauthenticated \
          --service-account=run-deployer@${PROJECT_ID}.iam.gserviceaccount.com \
          --concurrency=80 \
          --cpu=1 --memory=512Mi \
          --min-instances=0 --max-instances=1 \
          --set-env-vars "SPRING_PROFILES_ACTIVE=prod,JOURNEY_SERVICE_BASE=${_JOURNEY_SERVICE_BASE}" \
          --set-secrets "JOURNEY_SERVICE_CLIENT_ID=projects/${PROJECT_ID}/secrets/JOURNEY_SERVICE_CLIENT_ID:latest" \
          --set-secrets "JOURNEY_SERVICE_CLIENT_SECRET=projects/${PROJECT_ID}/secrets/JOURNEY_SERVICE_CLIENT_SECRET:latest" \
          --set-secrets "MCP_API_KEY=projects/${PROJECT_ID}/secrets/MCP_API_KEY:latest"

images:
  # This field should only contain the base image name without unresolved dynamic tags.
  # Cloud Build uses this to know which image repository to grant push permissions to.
  - "europe-west6-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE_NAME}"
