options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _REGION: "europe-west6"
  _SERVICE: "chattender-fahrplan-mcp"
  _REPO: "apps"
  _IMAGE_NAME: "chattender-fahrplan-mcp"
  _JOURNEY_SERVICE_BASE: "https://journey-service-int.api.sbb.ch"
  _PROJECT_NUMBER: "971368006395" # <--- ADD THIS SUBSTITUTION

steps:
  # Build Image mit Paketo Buildpacks (kein Dockerfile nötig)
  - name: gcr.io/k8s-skaffold/pack
    args:
      - build
      - "europe-west6-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE_NAME}:commit-$SHORT_SHA"
      - "--path=."
      - "--builder=gcr.io/buildpacks/builder:google-22"
    env:
      - GOOGLE_RUNTIME_VERSION=21

  # Deploy auf Cloud Run
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: bash
    args:
      - -c
      - |
        gcloud run deploy ${_SERVICE} \
          --image europe-west6-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE_NAME}:commit-$SHORT_SHA \
          --region ${_REGION} \
          --allow-unauthenticated \
          --service-account=run-deployer@${PROJECT_ID}.iam.gserviceaccount.com \
          --concurrency=80 \
          --cpu=1 --memory=512Mi \
          --min-instances=0 --max-instances=1 \
          --set-env-vars "SPRING_PROFILES_ACTIVE=prod,JOURNEY_SERVICE_BASE=${_JOURNEY_SERVICE_BASE}" \
          --set-secrets "JOURNEY_SERVICE_CLIENT_ID=projects/${_PROJECT_NUMBER}/secrets/JOURNEY_SERVICE_CLIENT_ID:latest" \
          --set-secrets "JOURNEY_SERVICE_CLIENT_SECRET=projects/${_PROJECT_NUMBER}/secrets/JOURNEY_SERVICE_CLIENT_SECRET:latest" \
          --set-secrets "MCP_API_KEY=projects/${_PROJECT_NUMBER}/secrets/MCP_API_KEY:latest"

images:
  - "europe-west6-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE_NAME}"
